-- 조건에 부합하는 중고거래 댓글 조회하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/164673
SELECT USED_GOODS_BOARD.TITLE, USED_GOODS_BOARD.BOARD_ID,
USED_GOODS_REPLY.REPLY_ID, USED_GOODS_REPLY.WRITER_ID,
USED_GOODS_REPLY.CONTENTS, DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE,"%Y-%m-%d") as CREATED_DATE
FROM (USED_GOODS_BOARD INNER JOIN USED_GOODS_REPLY)
WHERE USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
and USED_GOODS_BOARD.CREATED_DATE like '%2022-10%'
order by USED_GOODS_REPLY.CREATED_DATE asc, TITLE asc
